name: Generate Snek

on:
  # schedule:
    # - cron: "0 */6 * * *"  # 6時間ごとに実行（フォーマット修正）
  workflow_dispatch:  # 手動実行用

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3  # リポジトリをチェックアウト（追加）
      
      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snek-dark.svg?palette=github-dark&color_snake=blue&color_dots=#0d1117,#0e4429,#006d32,#26a641,#39d353
            dist/snek-light.svg?palette=github-light&color_snake=lightblue&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: snek
          path: dist
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: snek
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
